server:
  servlet:
    context-path: "/api"

#spring:
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yml
#    url:
#    user:
#    password:
#    driver-class-name: org.postgresql.Driver

#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect