server:
  port: 8443
  # Self-signed certificate for local development/deployment only!!!
  # (we use HttpOnly cookies so we need https for browsers to accept the cookie)
  ssl:
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: localdev
    key-alias: devcert

  servlet:
    context-path: "/api"


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}

springdoc:
  api-docs:
    enabled: false

mail:
  host: smtp.gmail.com
  port: 587
  debug: true
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
